#!/usr/bin/env python

VERSION = "0.1"

def init(n):
	"""
	init (n >= 2) :
	for n:
		mkdir $n/testnet3
		cp data-template/testnet3/* $n/testnet3
		cp data-template/bitcoin.conf $n/bitcoin.conf
		#do some magic on $n/bitcoin.conf
			#replace ports
	"""
	return

def clean(n):
	"""
	clean (n=id or n=null/ALL):
		for n:
			rm -rf $n/

		init()
	"""
	return


def main():
	print ("TESTNET-BOX v%s" % VERSION)



	pass

if __name__ == "__main__":
    main()